version: 2
updates:

  # Github Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly

  # curator
  - package-ecosystem: npm
    directory: "/curator/"
    schedule:
      interval: monthly

  # web
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
