on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'web/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Dependencies setup
        run: cd web && npm install --save-exact
      - name: publish
        run: web/publish.sh
      - name: Preserve in Wayback Machine
        run: |
          for changed_file in $(git diff --name-only)
          do
            if [[ "${changed_file}" == docs/*.html ]] && [ "${changed_file}" != "docs/curated/index.html" ]
            then
              ABSOLUTE_PATH_WEB="${changed_file#docs/}"
              RELATEIVE_PATH_WEB="${ABSOLUTE_PATH_WEB%index\.html}"

                curl --request POST \
                  --url https://web.archive.org/save/ \
                  --header 'Content-Type: application/x-www-form-urlencoded' \
                  --header 'Accept: application/json' \
                  --header 'Authorization: LOW ${{ secrets.WAYBACK_S3_ACCESS_KEY }}:${{ secrets.WAYBACK_S3_SECRET_KEY }}' \
                  --data "url=https://iyaki.ar/${RELATEIVE_PATH_WEB}" \
                  --data capture_all=on \
                  --data capture_outlinks=on \
                  --data capture_screenshot=on
            fi
          done
      - uses: stefanzweifel/git-auto-commit-action@v5
