on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'docs'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Generate the sitemap
        id: sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          path-to-root: docs
          base-url-path: https://iyaki.ar/
      - uses: stefanzweifel/git-auto-commit-action@v4
