on:
    workflow_dispatch:
    page_build:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: atymic/sitemap-ping-action@master
        with:
          sitemap-url: https://iyaki.ar/sitemap.xml
